### ISSUE TITLE
Some puzzle about the loc_head  and cls_head

### ISSUE THREAD

**Issue by holyhao** [silkylove/ObjectDetection#1]
Thanks for your work. I have some puzzle about the head part. I know that diffrent layers of  out the FPN  do not share the same location and classification part, and some methods like retinanet share the same part ,so do you have some expriments and some conclusion about use or not use share head.

**Comment by silkylove** [comment]
Thank you for your asking. I personally think that not sharing the same loc and cls parts would be fine as they are at different scales, so sharing would cause difficulties to learn the scales, maybe in the future I will do the comparision on fpnssd512.

**Comment by holyhao** [comment]
Thanks for your reply. I try to train the model on voc07+voc12(trainval) and test on voc07(test)，I just get 75% at IoU threshold 0.5, it is a lot worse than the paper. Do you have some ideas about this.

**Comment by silkylove** [comment]
I also got 75mAP which was very low, especially in class bottle which is usually small. I guess the reason may come from data augmentation. I will look at other implementations, then reply you later.
By the way, you got your 75mAP by running my code for the first time? I also got this result when runing for the first time after re-implementing the original code. If this happened, I do not know why the original author could get 81mAP, maybe tuning for a long time. :)

**Comment by holyhao** [comment]
Yeah, the original implement have many bugs  and their shared weights did not work well. So,I used your code for training.  By the way , recently，I am training a two classes task (object or not). I want to add some images that do not contain any object as the background . so, how can I put these images in training, and the images that do not contain any object can calculate the loss well? Looking forward your answer.

**Comment by silkylove** [comment]
Actually, you can refer to this [line](https://github.com/silkylove/ObjectDetection/blob/master/transforms/random_crop.py#L51) in random_crop.py. In random_crop.py, if the cropped image do not contain any objects, than we will set the bbox to be [all zero](https://github.com/silkylove/ObjectDetection/blob/master/transforms/random_crop.py#L52) and the coresponding label also to be [all zero](https://github.com/silkylove/ObjectDetection/blob/master/transforms/random_crop.py#L53). So in your case, you can simply set the bbox and label to be like this form and to do some augmentations you want.

**Comment by holyhao** [comment]
@silkylove  Correct me if am wrong. 0 should mean the first class object?    [https://github.com/silkylove/ObjectDetection/blob/cdeb044f285204f2a5eed1d7f33d6ac18629716f/models/fpnssd/bbox_coder.py#L64](url) It shows that labels ranges[0,20) and after this line ,0 then means the negatives.  So before that 0 means the first class?

**Comment by silkylove** [comment]
If you set the bbox to be all zero, then you will not find any box, i.e. index will be -1 for all pre-defined bbox, so they all will be set to [zero](https://github.com/silkylove/ObjectDetection/blob/master/models/fpnssd/bbox_coder.py#L65) which means background. And normally, the class will start from 1 in [this](https://github.com/silkylove/ObjectDetection/blob/master/models/fpnssd/bbox_coder.py#L64) if you find any pre-defined bbox who's iou is satisfied with some criterions with ground truth bbox, i.e. object.

**Comment by holyhao** [comment]
@silkylove  That is clear and tank you very much.
